// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace App.Model.Models;

public partial class Tarea
{
    public int Id { get; set; }

    public string Descripcion { get; set; }

    public string Estatus { get; set; }

    public DateTime FechaLimite { get; set; }

    public DateTime? FechaCreacion { get; set; }
}